async (page) => {
  let checks=0;
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  const assert=(value,label)=>{if(!value)throw new Error(label);checks++;};
  const url='http://127.0.0.1:4187/demo5/';
  await page.goto('about:blank');const cdp=await page.context().newCDPSession(page);await cdp.send('Storage.clearDataForOrigin',{origin:'http://127.0.0.1:4187',storageTypes:'local_storage'});await cdp.detach();await page.setViewportSize({width:1280,height:900});await page.goto(url);
  await page.emulateMedia({reducedMotion:'reduce'});
  const saved=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('demo5.sound-stitch.v1')));
  const slots=async()=>{const s=await saved();return s.puzzles[['sprout','walk','lantern'][s.levelIndex]].slots;};
  const nav=i=>page.locator('#levels button').nth(i).click();
  const choose=id=>page.locator(`[data-gem="${id}"]`).click();
  const put=async(id,index)=>{await page.locator(`[data-gem="${id}"]`).focus();await page.keyboard.press(String(index+1));};
  const solutions=[['s-kite','s-pebble'],['w-sand','w-cloud','w-reed'],['l-moss','l-rain','l-fern','l-shell']];
  assert(await page.locator('.gem').count()===2,'initial gems');
  assert(await page.locator('#stop').isDisabled(),'no autoplay');
  assert(await page.locator('#move-right').isDisabled(),'no active move');
  await choose('s-kite');assert(await page.locator('#stop').isEnabled(),'tap plays');
  await page.locator('#place-active').click();assert((await slots()).includes('s-kite'),'tap alternative places');
  await page.locator('#return-active').click();assert((await slots()).every(id=>!id),'tap removes');
  await put('s-kite',0);await put('s-pebble',1);
  await page.locator('#play-order').click();assert(!await page.locator('#listening-room').evaluate(el=>el.open),'no reward before judge');await page.locator('#stop').click();
  await put('s-kite',1);assert(JSON.stringify(await slots())===JSON.stringify(['s-pebble','s-kite']),'keyboard swap');
  assert(await page.locator('.light-link').count()===1,'wrong order connects');
  await page.locator('#check').click();assert((await page.locator('#feedback').textContent()).includes('もう少し'),'wrong verdict');
  assert(!await page.locator('#listening-room').evaluate(el=>el.open),'wrong no room');
  await put('s-kite',0);await page.locator('#check').click();
  await page.waitForFunction(()=>document.getElementById('listening-room').open);
  assert(await page.locator('.room-gem').count()===2,'all stones glow');
  assert(await page.locator('#room-stop').evaluate(el=>el===document.activeElement),'room focus');
  await page.locator('#room-mute').click();assert(await page.locator('#room-mute').getAttribute('aria-pressed')==='true','room mute');
  await page.locator('#room-volume').fill('40');assert((await saved()).volume===.4,'room volume saved');
  await page.keyboard.press('Escape');assert(!await page.locator('#listening-room').evaluate(el=>el.open),'escape closes room');
  assert(await page.locator('#check').evaluate(el=>el===document.activeElement),'focus restored');
  await page.locator('#mute').click();
  await page.locator('#reference').click();await page.waitForTimeout(100);
  assert(await page.locator('.gem.is-playing').count()===0,'reference hides sequence');
  await page.locator('#stop').click();
  await page.reload();assert(JSON.stringify(await slots())===JSON.stringify(solutions[0]),'reload restores slots');
  assert((await saved()).solved.includes('sprout'),'reload solved');
  assert(await page.locator('#volume').inputValue()==='40','reload loudness');
  // Actual pointer capture/drag paths. One gem stays one node throughout.
  await nav(2);
  const drag=async(id,target,mode='up')=>{
    const box=await page.locator(`[data-gem="${id}"]`).boundingBox();
    await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();
    await page.mouse.move(target.x,target.y,{steps:8});
    if(mode==='cancel')await page.locator(`[data-gem="${id}"]`).dispatchEvent('pointercancel');
    else if(mode==='escape')await page.keyboard.press('Escape');
    await page.mouse.up();
  };
  const target=async index=>page.evaluate(i=>{const b=document.getElementById('gem-stage'),r=b.getBoundingClientRect();return{x:r.left+(i+.5)*b.clientWidth/4,y:r.top+b.clientHeight*.29};},index);
  await drag('l-moss',await target(0));assert((await slots())[0]==='l-moss','drag places');
  assert(await page.locator('#stop').isDisabled(),'drag no unsolicited audio');
  await drag('l-rain',await target(1));await drag('l-moss',await target(1));
  assert(JSON.stringify((await slots()).slice(0,2))===JSON.stringify(['l-rain','l-moss']),'drag swaps');
  const before=JSON.stringify(await slots());
  await drag('l-moss',{x:2,y:4});assert(JSON.stringify(await slots())===before,'outside cancel');
  await drag('l-moss',await target(3),'cancel');assert(JSON.stringify(await slots())===before,'pointercancel keeps stones');
  await drag('l-moss',await target(3),'escape');assert(JSON.stringify(await slots())===before,'escape cancel');
  assert(await page.locator('.gem').count()===4,'no missing/duplicate stones');
  const shelf=await page.evaluate(()=>{const b=document.getElementById('gem-stage'),r=b.getBoundingClientRect();return{x:r.left+40,y:r.top+b.clientHeight*.85};});
  await drag('l-moss',shelf);assert(!(await slots()).includes('l-moss'),'drag removes to shelf');
  for(let i=0;i<4;i++)await put(solutions[2][i],i);
  assert(await page.locator('.light-link').count()===3,'adjacency 3 links');
  await page.locator('#check').click();await page.waitForFunction(()=>document.getElementById('listening-room').open);
  assert(await page.locator('.room-gem').count()===4,'four gem completion');
  await page.locator('#room-stop').click();assert(await page.locator('#stop').isDisabled(),'explicit room stop');
  await nav(1);for(let i=0;i<3;i++)await put(solutions[1][i],i);await page.locator('#check').click();
  await page.waitForFunction(()=>document.getElementById('listening-room').open);await page.locator('#room-stop').click();
  assert((await saved()).solved.length===3,'all levels judged');
  // Changing level cancels future audio; hidden -> return never autoplays.
  await page.locator('#reference').click();await page.waitForTimeout(100);await nav(0);
  assert(await page.locator('#stop').isDisabled(),'level stops sound');
  await page.locator('#reference').click();await page.waitForTimeout(100);
  await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));});
  assert(await page.locator('#stop').isDisabled(),'background stops');
  await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:false});document.dispatchEvent(new Event('visibilitychange'));});
  assert(await page.locator('#stop').isDisabled(),'foreground does not autoplay');
  await page.locator('#reference').click();await page.waitForFunction(()=>!document.getElementById('stop').disabled);assert(await page.locator('#stop').isEnabled(),'explicit resume works');await page.locator('#stop').click();
  await page.locator('.help summary').click();await page.locator('#shuffle').click();
  const order=await slots();assert(order.every(Boolean)&&order[0]!=='s-kite','shuffle cannot solve itself');
  await page.locator('#clear').click();assert((await slots()).every(id=>!id),'clear all');
  await page.locator('.help summary').click();
  const mobile=[];
  for(const viewport of [{width:390,height:844},{width:390,height:664},{width:320,height:568}]) {
    await page.setViewportSize(viewport);
    for(let i=0;i<3;i++) {
      await nav(i);await page.evaluate(()=>scrollTo(0,0));
      const metric=await page.evaluate(()=>({width:document.documentElement.scrollWidth,visible:['gem-stage','reference','play-order','check','stop'].every(id=>{const r=document.getElementById(id).getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight;}),touch:['reference','play-order','check','stop','place-active','move-left','move-right','return-active'].every(id=>document.getElementById(id).getBoundingClientRect().height>=44)}));
      assert(metric.width<=viewport.width,'no horizontal overflow');assert(metric.visible,`core visible ${viewport.width}x${viewport.height}/level${i}`);assert(metric.touch,'44px controls');
      const first=solutions[i][0];await choose(first);await page.evaluate(()=>scrollTo(0,0));
      assert(await page.locator('#stop').evaluate(el=>el.getBoundingClientRect().bottom<=innerHeight),'after tap core visible');await page.locator('#stop').click();
      mobile.push({viewport,level:i+1,...metric});
    }
  }
  await page.screenshot({path:'output/playwright/polish-320.png'});
  const noMotion=await page.evaluate(()=>document.getAnimations().filter(a=>a.playState==='running').length===0);
  assert(noMotion,'reduced motion has no active animation');
  await page.evaluate(()=>document.documentElement.style.fontSize='200%');
  assert(await page.evaluate(()=>document.documentElement.scrollHeight>innerHeight),'enlarged text scrolls');
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'enlarged text no overflow');
  await page.locator('#stop').scrollIntoViewIfNeeded();assert(await page.locator('#stop').isVisible(),'enlarged controls reachable');
  await page.evaluate(()=>document.documentElement.style.fontSize='');
  assert(errors.length===0,`page errors: ${errors}`);
  return {checks,errors,mobile};
}
